<a href="https://colab.research.google.com/github/smiledinisa/sk_learn/blob/master/sk_learn003_datapreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive/


In [ ]:
# 数据预处

# 数据预处理 Preprocessing & Impute

## preprocessing.MinMaxScaler 将数据归一化。

In [3]:
from sklearn.preprocessing import MinMaxScaler

data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

import pandas as pd

pd.DataFrame(data)


0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [4]:
scaler = MinMaxScaler()
scaler = scaler.fit(data)
result = scaler.transform(data) # 两步
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [6]:
result_ = scaler.fit_transform(data) # 一步达成。
result_

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [7]:
# 将归一化的结果逆转。

scaler.inverse_transform(result)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [8]:
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler(feature_range=[5,10])
result = scaler.fit_transform(data)
result

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [ ]:
# 注意，当x数量太大，fit可能会报错，这时候需要改用partial_fit 来作为接口。

# preprocessing.StandardScaler

# 数据标准化。

In [9]:
from sklearn.preprocessing import StandardScaler

data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]


In [10]:
scaler = StandardScaler()
scaler = scaler.fit(data)
result = scaler.transform(data)
result

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [11]:
scaler.mean_

array([-0.125,  9.   ])

In [13]:
scaler.var_

array([ 0.546875, 35.      ])

# 数据缺失值


In [14]:
import pandas as pd

In [15]:
data = pd.read_csv('/content/drive/My Drive/titannike/Narrativedata.csv', index_col=0)
data.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [16]:
# 该数据有三个特征，两个字符型，一个数字型，最后一个是标签。


# impute.SimpleImputer 填补缺失值用过这个方法。

class  sklearn.impute.SimpleImputer (  
  missing_values=nan,   
  strategy=’mean’,   
  fill_value=None,   
  verbose=0,  
  copy=True)  


四个参数：  
missing_values 告诉simpleimputer 缺失值长什么样子。  
strategy： 
使用mean 均值填补。    

1.   median 中值。
2.   most_frequent 众数填补。  
3. constant 常数填补。 

fillvalue: 只有当constant时候可用。 


copy:   默认true，创建副本，否则将原矩阵进行改变。 

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       714 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [18]:
# 我们从信息中可以看到那些类有缺失值，缺失值多少等等信息。

age = data.loc[:,'Age'].values.reshape(-1,1)

age[:20]

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [nan],
       [54.],
       [ 2.],
       [27.],
       [14.],
       [ 4.],
       [58.],
       [20.],
       [39.],
       [14.],
       [55.],
       [ 2.],
       [nan],
       [31.],
       [nan]])

In [19]:
from sklearn.impute import SimpleImputer

In [21]:

imp_mean = SimpleImputer()
imp_median = SimpleImputer(strategy='median')
imp_0 = SimpleImputer(strategy='constant', fill_value=0)


imp_mean = imp_mean.fit_transform(age)
imp_median = imp_median.fit_transform(age)
imp_0 = imp_0.fit_transform(age)

imp_mean[:20]

array([[22.        ],
       [38.        ],
       [26.        ],
       [35.        ],
       [35.        ],
       [29.69911765],
       [54.        ],
       [ 2.        ],
       [27.        ],
       [14.        ],
       [ 4.        ],
       [58.        ],
       [20.        ],
       [39.        ],
       [14.        ],
       [55.        ],
       [ 2.        ],
       [29.69911765],
       [31.        ],
       [29.69911765]])

In [22]:
imp_median[:20]

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [28.],
       [54.],
       [ 2.],
       [27.],
       [14.],
       [ 4.],
       [58.],
       [20.],
       [39.],
       [14.],
       [55.],
       [ 2.],
       [28.],
       [31.],
       [28.]])

In [23]:
imp_0[:20]

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [ 0.],
       [54.],
       [ 2.],
       [27.],
       [14.],
       [ 4.],
       [58.],
       [20.],
       [39.],
       [14.],
       [55.],
       [ 2.],
       [ 0.],
       [31.],
       [ 0.]])

In [24]:
data.loc[:,'Age'] = imp_median
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [28]:
# 从信息可以看出，已经被填补完成。
# 但是embarked 好像还差几个缺失值。


Embarked = data.loc[:,'Embarked'].values.reshape(-1,1)
imp_mode = SimpleImputer(strategy='most_frequent')
data.loc[:,'Embarked'] = imp_mode.fit_transform(Embarked)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  891 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [31]:
# 全部填充完全。
# 其实用numpy和pandas来进行值的填补更加简单。
import pandas as pd

data = pd.read_csv('/content/drive/My Drive/titannike/Narrativedata.csv', index_col=0)
data.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [53]:
data.loc[:,'Age'] = data.loc[:,'Age'].fillna(data.loc[:,'Age'].median())


data.dropna(axis=0, inplace=True)

data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       889 non-null    float64
 1   Sex       889 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  889 non-null    int64  
dtypes: float64(1), int64(1), object(2)
memory usage: 34.7+ KB


In [40]:
data['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [43]:
data.loc[:,'Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

# 2.3 处理分类型特征：编码与哑变量


## 将文字型数据转换成数值型数字。

# preprocessing.LabelEncoder

In [44]:
## preprocessing.LabelEncoder 标签专用，能够将分类转换成数值分类
from sklearn.preprocessing import LabelEncoder

y = data.iloc[:,-1]

le = LabelEncoder()
le = le.fit(y)
label = le.transform(y)

le.classes_

array(['No', 'Unknown', 'Yes'], dtype=object)

In [45]:
label

array([0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       2, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 0, 0, 0, 2,
       2, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 1, 0,
       0, 2, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 2, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 0, 0,
       1, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0,
       2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 2, 0, 1,
       0, 0, 1, 2, 2, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2,

In [46]:
data.iloc[:,-1] = label

In [47]:
data.head()

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

In [73]:
# 可以简单直接的写成这样。
from sklearn.preprocessing import LabelEncoder
data.iloc[:,-1] = LabelEncoder().fit_transform(data.iloc[:,-1])
data = data.dropna()
data.head()

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

# preprocessing.OrdinalEncoder 特征专用


In [55]:
# preprocessing.OrdinalEncoder

from sklearn.preprocessing import OrdinalEncoder

data_ = data.copy()

data_.head()

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

In [74]:
data_.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       889 non-null    float64
 1   Sex       889 non-null    float64
 2   Embarked  889 non-null    float64
 3   Survived  889 non-null    int64  
dtypes: float64(3), int64(1)
memory usage: 34.7 KB


In [59]:

data_.iloc[:,1:-1] = OrdinalEncoder().fit_transform(data_.iloc[:,1:-1])

data_.head()

Age  Sex  Embarked  Survived
0  22.0  1.0       2.0         0
1  38.0  0.0       0.0         2
2  26.0  0.0       2.0         2
3  35.0  0.0       2.0         2
4  35.0  1.0       2.0         0

In [60]:
OrdinalEncoder().fit(data_.iloc[:,1:-1]).categories_  #每个特征的分类，数字类型。

[array([0., 1.]), array([0., 1., 2.])]

# preprocessing.OneHotEncoder
# 哑变量

# 舱门没有大小之分，也不能相互运算，这种变量成为：名义变量。
# 学历，有高低，但是不能相加减运算，这种变量成为有序变量。
# 体重，可以相加相减，这种变量成为有距变量。

# 将本来不能相互比较的变量转换成可以相互比较的数字变量，这为原来的标签附加了更多的特性，丢失了原来特征的独特性。

#所以需要哑变量，专门负责。

In [61]:
data.head()

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

In [62]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       889 non-null    float64
 1   Sex       889 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  889 non-null    int64  
dtypes: float64(1), int64(1), object(2)
memory usage: 34.7+ KB


In [64]:
from sklearn.preprocessing import OneHotEncoder

x = data.iloc[:,1:-1]

In [65]:
enc = OneHotEncoder(categories='auto').fit(x)

result = enc.transform(x).toarray()
result

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [68]:
result.shape

(889, 5)

In [70]:
# 我们可以看出，OneHot 直接将两个特征一起转换成了哑变量。
# 我们也可以一步到位。
result = OneHotEncoder(categories='auto').fit_transform(x).toarray()
result

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [71]:
enc.get_feature_names

<bound method OneHotEncoder.get_feature_names of OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)>

In [78]:
newdata = pd.concat([data, pd.DataFrame(result)], axis=1)
newdata = newdata.dropna()
newdata

Age     Sex Embarked  Survived    0    1    2    3    4
0    22.0    male        S       0.0  0.0  1.0  0.0  0.0  1.0
1    38.0  female        C       2.0  1.0  0.0  1.0  0.0  0.0
2    26.0  female        S       2.0  1.0  0.0  0.0  0.0  1.0
3    35.0  female        S       2.0  1.0  0.0  0.0  0.0  1.0
4    35.0    male        S       0.0  0.0  1.0  0.0  0.0  1.0
..    ...     ...      ...       ...  ...  ...  ...  ...  ...
884  25.0    male        S       0.0  0.0  1.0  0.0  0.0  1.0
885  39.0  female        Q       0.0  1.0  0.0  0.0  0.0  1.0
886  27.0    male        S       0.0  1.0  0.0  0.0  0.0  1.0
887  19.0  female        S       2.0  0.0  1.0  1.0  0.0  0.0
888  28.0  female        S       0.0  0.0  1.0  0.0  1.0  0.0

[887 rows x 9 columns]

In [79]:
newdata.drop(['Sex','Embarked'], axis=1, inplace=True)

In [80]:
newdata.columns = ["Age","Survived","Female","Male","Embarked_C","Embarked_Q","Embarked_S"]

newdata.head()

Age  Survived  Female  Male  Embarked_C  Embarked_Q  Embarked_S
0  22.0       0.0     0.0   1.0         0.0         0.0         1.0
1  38.0       2.0     1.0   0.0         1.0         0.0         0.0
2  26.0       2.0     1.0   0.0         0.0         0.0         1.0
3  35.0       2.0     1.0   0.0         0.0         0.0         1.0
4  35.0       0.0     0.0   1.0         0.0         0.0         1.0

![链接文字](https://img-blog.csdnimg.cn/20200824173944413.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2dhb2N1aTg4Mw==,size_16,color_FFFFFF,t_70#pic_center)

![链接文字](https://img-blog.csdnimg.cn/2020082417401672.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2dhb2N1aTg4Mw==,size_16,color_FFFFFF,t_70#pic_center)



# 2.4 处理连续型特征，二值化和分段。

#sklearn.preprocessing.Binarizer

In [89]:
# 将年龄二值化
data2 = data.copy()
from sklearn.preprocessing import Binarizer
x = data2.iloc[:,0].values.reshape(-1,1)
transformer = Binarizer(threshold=30).fit_transform(x)

transformer[:10,:]

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.]])

# preprocessing.KBinsDiscretizer


将连续型变量划分为分类变量的类，能够将连续变量排序后按顺序分箱后编码。

包含三个参数：

# 1. n_bins ： 每个特征分箱的个数，默认为5， 一次会被运用到所有导入的特征。

# 2. encode : 默认为one-hot, 编码方式有三种： 
- onehot 做哑变量，之后返回一个稀疏矩阵，每一列是一个特征中的一个类别，含有该
类别的样本表示为1，不含的表示为0
- ordinal 每个特征的每个箱都被编码为一个整数，返回每一列是一个特征，每个特征下含
有不同整数编码的箱的矩阵
- onehot-dense 做哑变量，之后返回一个密集数组。

# 3. strategy ： 默认为quantile,定义箱宽的方式。
- "uniform"：表示等宽分箱，即每个特征中的每个箱的最大值之间的差为
(特征.max() - 特征.min())/(n_bins)

- "quantile"：表示等位分箱，即每个特征中的每个箱内的样本数量都相同

- "kmeans"：表示按聚类分箱，每个箱中的值到最近的一维k均值聚类的簇心得距离都相同

In [92]:
from sklearn.preprocessing import KBinsDiscretizer

x = data.iloc[:,0].values.reshape(-1,1)
# x 是年龄。

In [96]:
est = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform')
est.fit_transform(x)[:10,:]

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.]])

In [100]:
est = KBinsDiscretizer(n_bins=3, encode='onehot', strategy='uniform')
est.fit_transform(x).toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [102]:
est = KBinsDiscretizer(n_bins=3, encode='onehot-dense', strategy='uniform')
est.fit_transform(x)

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

# 3 特征选择 feature_selection.

当数据处理完成后，就要开始特征工程了。